from dataclasses import dataclass, field
from typing import Dict, Any, Tuple
import json
import hashlib
import numpy as np


# ----------------
# helper utilities
# ----------------
def _normalize_text(text: str) -> str:
    return " ".join((text or "").strip().lower().split())


def _stable_sig(text: str) -> str:
    return hashlib.sha256(_normalize_text(text).encode("utf-8")).hexdigest()


def _safe_parse_json_dict(raw_text: str) -> Tuple[Dict[str, Any], str]:
    raw = (raw_text or "").strip()

    try:
        obj = json.loads(raw)
        if isinstance(obj, dict):
            return obj, "json_ok"
    except Exception:
        pass

    try:
        start = raw.find("{")
        end = raw.rfind("}")
        if start != -1 and end != -1 and end > start:
            obj = json.loads(raw[start:end + 1])
            if isinstance(obj, dict):
                return obj, "json_extracted"
    except Exception:
        pass

    # last-resort fallback
    return {
        "name": "unstructured_persona",
        "style": raw,
        "tone": "unknown",
        "domain": "unknown",
        "obfuscation_strategy": "unknown",
    }, "raw_text"


def _persona_to_canonical_text(fields: Dict[str, Any], parse_status: str) -> str:
    if parse_status == "raw_text":
        return str(fields.get("style", "")).strip()

    keys = ["name", "style", "tone", "domain", "obfuscation_strategy"]
    parts = []
    for k in keys:
        v = fields.get(k)
        if v:
            parts.append(f"{k}: {str(v).strip()}")
    return " | ".join(parts)


def _l2_normalize(v: np.ndarray) -> np.ndarray:
    return v / (np.linalg.norm(v) + 1e-12)


# ----------------
# persona object
# ----------------

@dataclass(frozen=True)
class Persona:
    """
    Stateless persona generated by the attacker LLM.

    One persona corresponds to one mutation/refinement step.
    """

    pid: str
    canonical_text: str

    fields: Dict[str, Any]

    raw_output: str
    parse_status: str

    embedding: np.ndarray = field(repr=False)

    iteration_id: int
    refinement_iter: int


    # ------------
    # constructors
    # ------------

    @staticmethod
    def from_llm_output(
        raw_output: str,
        embedder: Any,
        *,
        iteration_id: int,
        refinement_iter: int,
    ) -> "Persona":

        fields, status = _safe_parse_json_dict(raw_output)

        canonical = _persona_to_canonical_text(fields, status)
        pid = _stable_sig(canonical)

        emb = embedder.encode([canonical], normalize_embeddings=True)[0]
        emb = _l2_normalize(np.asarray(emb, dtype=np.float32))

        return Persona(
            pid=pid,
            canonical_text=canonical,
            fields=fields,
            raw_output=raw_output.strip(),
            parse_status=status,
            embedding=emb,
            iteration_id=iteration_id,
            refinement_iter=refinement_iter,
        )


    # -----------------------
    # interfaces
    # -----------------------

    def as_dict_for_attacker(self) -> Dict[str, Any]:
        """
        Minimal JSON passed to the attacker for prompt mutation.
        """
        return dict(self.fields)


    def as_dict_for_archive(self) -> Dict[str, Any]:
        """
        Safe JSON-serializable representation for logging and later analysis.
        """
        d = dict(self.fields)
        d["_pid"] = self.pid
        d["_canonical_text"] = self.canonical_text
        d["_parse_status"] = self.parse_status
        d["_iteration_id"] = self.iteration_id
        d["_refinement_iter"] = self.refinement_iter
        return d
