from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Tuple
import json
import hashlib
import numpy as np


# ---------------------------------------------------------------------------
# Internal utilities
# ---------------------------------------------------------------------------
def _normalize_text(text: str) -> str:
    return " ".join((text or "").strip().lower().split())


def _stable_sig(text: str) -> str:
    return hashlib.sha256(_normalize_text(text).encode("utf-8")).hexdigest()


def _safe_parse_json_dict(raw_text: str) -> Tuple[Dict[str, Any], str]:
    raw = (raw_text or "").strip()

    try:
        obj = json.loads(raw)
        if isinstance(obj, dict):
            return obj, "json_ok"
    except Exception:
        pass

    try:
        start, end = raw.find("{"), raw.rfind("}")
        if start != -1 and end > start:
            obj = json.loads(raw[start:end + 1])
            if isinstance(obj, dict):
                return obj, "json_extracted"
    except Exception:
        pass

    return {
        "name": "unstructured_persona",
        "style": raw,
        "tone": "unknown",
        "domain": "unknown",
        "obfuscation_strategy": "unknown",
    }, "raw_text"


def _persona_to_canonical_text(fields: Dict[str, Any], parse_status: str) -> str:
    if parse_status == "raw_text":
        return str(fields.get("style", "")).strip()
    keys = ["name", "style", "tone", "domain", "obfuscation_strategy"]
    return " | ".join(
        f"{k}: {str(fields[k]).strip()}"
        for k in keys if fields.get(k)
    )


def _l2_normalize(v: np.ndarray) -> np.ndarray:
    return v / (np.linalg.norm(v) + 1e-12)


# ---------------------------------------------------------------------------
# Persona
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Persona:
    """
    Stateless, immutable persona generated by the attacker LLM for one
    mutation/refinement step. Embeddings are stored for similarity checks
    but excluded from archive serialization.
    """
    pid:            str
    canonical_text: str
    fields:         Dict[str, Any]
    raw_output:     str
    parse_status:   str
    embedding:      np.ndarray = field(repr=False)
    iteration_id:   int
    refinement_iter: int

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------
    @staticmethod
    def from_llm_output(
        raw_output: str,
        embedder: Any,
        *,
        iteration_id: int,
        refinement_iter: int,
    ) -> Persona:
        fields, status = _safe_parse_json_dict(raw_output)
        canonical      = _persona_to_canonical_text(fields, status)
        pid            = _stable_sig(canonical)
        emb            = _l2_normalize(
            np.asarray(
                embedder.encode([canonical], normalize_embeddings=True)[0],
                dtype=np.float32,
            )
        )
        return Persona(
            pid=pid,
            canonical_text=canonical,
            fields=fields,
            raw_output=raw_output.strip(),
            parse_status=status,
            embedding=emb,
            iteration_id=iteration_id,
            refinement_iter=refinement_iter,
        )

    # ------------------------------------------------------------------
    # Interfaces
    # ------------------------------------------------------------------
    def as_dict_for_attacker(self) -> Dict[str, Any]:
        return dict(self.fields)

    def as_dict_for_archive(self) -> Dict[str, Any]:
        d = dict(self.fields)
        d["_pid"]            = self.pid
        d["_canonical_text"] = self.canonical_text
        d["_parse_status"]   = self.parse_status
        d["_iteration_id"]   = self.iteration_id
        d["_refinement_iter"] = self.refinement_iter
        return d